repo: 'dfreeman/release-it-troubleshooting'
github:
  release: true
  releaseName: 'v${version}'
  tokenRef: GITHUB_AUTH
plugins:
  release-it-yarn-workspaces: true
  release-it-lerna-changelog: true
